In [1]:
import numpy as np     
a=np.array([1,2,3,4])
b=np.array([2,5,8,3])
print(a*b)

[ 2 10 24 12]


In [3]:
import numpy as np
a=np.array([[1,4,7],[3,6,9],[9,6,3]])
b=np.array([[1,5,9],[8,5,2],[7,4,1]])
print("value of a :",a)
print("value of b :",b)
print("value of a*b:",a*b)
print("value of a+b:",a+b)
print("value of a**2",a**2)



value of a : [[1 4 7]
 [3 6 9]
 [9 6 3]]
value of b : [[1 5 9]
 [8 5 2]
 [7 4 1]]
value of a*b: [[ 1 20 63]
 [24 30 18]
 [63 24  3]]
value of a+b: [[ 2  9 16]
 [11 11 11]
 [16 10  4]]
value of a**2 [[ 1 16 49]
 [ 9 36 81]
 [81 36  9]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1,2,3],[2,4,6]])
print("dimesions of a: ",a.ndim) 
print("dimesions of b: ",b.ndim)# ndim-> number dimensions

dimesions od a:  1
dimesions of b:  2


In [4]:
import numpy as np 
a=np.array([1,2,3])
b=np.array([[1,2,3],[2,4,6]])
print(a.shape)
print(b.shape) # shape refer's the (rows,columns) of an given array

(3,)
(2, 3)


In [5]:
import numpy as np 
a=np.array([1,2,3],dtype='int16')
b=np.array([3,4,5])
print("type of a: ",a.dtype)
print("type of b: ",b.dtype)# by default numpy stores in int64 or int 32 datatype based on flatform oriented
                             # all modern uses int 64

type of a:  int16
type of b:  int64


In [6]:
import numpy as np 
a=np.array([1,2,3],dtype='int16')
b=np.array([3,4,5])
print("size of an array a in bytes: ",a.itemsize)
print("size of an array b in bytes: ",b.itemsize) # itemsize gives the size of each element in bytes

size of an array a in bytes:  2
size of an array b in bytes:  8


In [7]:
# number of bytes =size * itemsize
import numpy as np 
a=np.array([1,2,3],dtype='int16')
b=np.array([3,4,5])
print("size of an array a in bytes: ",a.nbytes)
print("size of an array b in bytes: ",b.nbytes) # number of bytes =size * itemsize
print("a", a.itemsize*a.size)
print("b",b.itemsize*b.size)

size of an array a in bytes:  6
size of an array b in bytes:  24
a 6
b 24


In [8]:
# to get an element access via indexing ex:[row,column]
import numpy as np
m=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("printing an element from array m: ",m[0,3]) # we can use negative indexing in it


printing an element from array m:  4


In [9]:
import numpy as np
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("printing an specific column from array m: ",c[:,3]) 
print("printing an specific row from an array: ",c[1,:])

printing an specific column from array m:  [4 9]
printing an specific row from an array:  [ 6  7  8  9 10]


In [ ]:
# formatting for a specific required elements [startIndex:endIndex:stepSize]
import numpy as np
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("formatting with 2: ",c[1,1:4:2])
print("formatting with 1: ",c[0:4:1,1])

formating with 2:  [7 9]
formating with 1:  [2 7]


In [11]:
import numpy as np
a=np.array([[1,3,5,7,9],[1,2,4,6,8]])
a[1,2]=30
print(a)
a[:,3]=45   
print(a)

[[ 1  3  5  7  9]
 [ 1  2 30  6  8]]
[[ 1  3  5 45  9]
 [ 1  2 30 45  8]]


In [12]:
import numpy as np
a= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
import numpy as np
a= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a[0,1,1])

4


In [14]:
import numpy as np
a= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a[:,1,:])

[[3 4]
 [7 8]]


In [15]:
import numpy as np
a= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a[:,0,:]=[[1,4],[5,3]]
print(a)

[[[1 4]
  [3 4]]

 [[5 3]
  [7 8]]]


In [16]:
import numpy as np
zeros=np.zeros((2,3),dtype='int32')   # we can create an array with intializing 0 for each element
print(zeros)

[[0 0 0]
 [0 0 0]]


In [17]:
import numpy as np
ones=np.ones((3,3))    # creation of array with 1 
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
import numpy as np
full=np.full((3,4),279,dtype='float32')  # we can create a array full of specifiec number 
print(full)

[[279. 279. 279. 279.]
 [279. 279. 279. 279.]
 [279. 279. 279. 279.]]


In [19]:
import numpy as np 
x=np.full(c.shape,4)   # or x=np.full_like(c,4)  both can perform same array fixtures
print(x)

[[4 4 4 4 4]
 [4 4 4 4 4]]


In [20]:
import numpy as np 
ukn=np.random.rand(2,4)   # this generate a random decimal in a given fixture
print(ukn)
ukn=np.random.random_sample(c.shape) # generates in a specific order of another array 
print(ukn)

[[0.98298994 0.7099086  0.30915632 0.45851971]
 [0.87984415 0.97927749 0.53005855 0.60449871]]
[[0.83729034 0.5629187  0.95332206 0.18509936 0.51591556]
 [0.9621823  0.03727488 0.75690492 0.60936054 0.68919681]]


In [ ]:
import numpy as np
max=np.random.randint(10,19,size =(1,5))  # syntax = (start,stop,size=(array dimensions))
print(max)

[[14 11 14 12 17]]


In [22]:
import numpy as np 
iden=np.identity(3)  # generates a identity matrix
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np 
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0)   # syntax= np.repeat(array,no_of_times,axis)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import numpy as np
# generate a array with ones in 5d
x=np.ones((5,5))
print(x)                                            # 11111
z=np.zeros((3,3))                                   # 10001
print(z)                                            # 10901
z[1,1]=9                                            # 10001
print(z)                                            # 11111
x[1:4,1:4]=z
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
import numpy as np 
a=np.array([1,2,3])
b=a
b[0]=123  # just modified b[0]=123 but not a instead use copy
print(a)
print(b)
c=np.array([1,2,4])
d=c.copy()
d[0]=123
print(c)
print(d)


[123   2   3]
[123   2   3]
[1 2 4]
[123   2   4]


In [7]:
import numpy as np
x=np.array([1,2,3,4])
print(np.cos(x))
print(np.sin(x))
print(np.tan(x))


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [ ]:
import numpy as np
x=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(x,b)       
print(np.matmul(x,b))   # matmul-> matrix multiplication with columns of 1st matrix = rows of second matrix

[[1 4 7]
 [3 6 9]
 [9 6 3]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [11]:
import numpy as np 
I=np.identity(4)
det=np.linalg.det(I)    # to find determinant of identity matrix
print(det)

1.0


In [ ]:
# functions that can be performed on matrix

import numpy as np
max=np.random.randint(1,10,size =(4,4)) 
print(max)
det=np.linalg.det(max)
print("determinant: ",det)
trace=np.linalg.trace(max)
print("trace: ",trace)
transpose=np.linalg.matrix_transpose(max)
print("transpose: ",transpose)
rank=np.linalg.matrix_rank(max)
print("rank: ",rank)
diagonal=np.linalg.diagonal(max)
print("diagonal: ",diagonal)
singular=np.linalg.vector_norm(max)
print(singular)

[[7 9 6 8]
 [3 2 9 4]
 [2 3 4 8]
 [7 9 6 1]]
determinant:  342.99999999999983
trace:  14
transpose:  [[7 3 2 7]
 [9 2 3 9]
 [6 9 4 6]
 [8 4 8 1]]
rank:  4
diagnol:  [7 2 4 1]
24.49489742783178


In [47]:
# statistics
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
minimum=np.min(a)
maximum=np.max(a)
print(maximum)
print(minimum)
sumation=np.sum(a)
print(sumation)

6
1
21


In [29]:
import numpy as np 
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
b=a.reshape((4,2))  # we can reshape an numpy array
print(b)

[[1 2 3 4]
 [6 7 8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [33]:
import numpy as np 
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
v3=np.array([9,10,11,12])
res=np.vstack([v1,v2,v3]) # vertical stack
res1=np.hstack([v1,v2,v3]) # horizontal stack
print(res)
print(res1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
import numpy as np 
v=np.genfromtxt('data.txt',delimiter=',',dtype=int)
print(v)

[    1     2     3    12    13    15   161 23453  4724   246  4356     4
  7473    23   458    95   673   452  6527   878    75  6354  3464  7757
     4]


In [46]:
v>50
v[v>50 ]
((v>50) & (v<100))

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False])

In [ ]:
import numpy as np 
a=np.array([1,2,3,5,6,7,8,9,12])   # index with a list in numpy
print(a[[1,4,7]])

[2 6 9]
